runtime: php55
api_version: 1
threadsafe: true

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

- url: /
  script: index.php

- url: /
  script: connect.php 

- url: /
  script: footer.php 

- url: /
  script: functions.php  

- url: /
  script: main.php 

- url: /
  script: nav-bar.php 

- url: /
  script: read.php 

- url: /
  script: tables.php 

- url: /
  script: update.php 

- url: /
  script: wish.php 

- url: /stylesheets
  static_dir: stylesheets